//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABATS.AppsTalk.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABATS.AppsTalk.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Metadata - The Engine Failed To Consume Source Adapter : [Process Code={0}].
        /// </summary>
        internal static string Message_Consume_Source_Failed {
            get {
                return ResourceManager.GetString("Message_Consume_Source_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Engine failed to fetch the Integration Process Metadata : [Process Code={0}].
        /// </summary>
        internal static string Message_Fetch_integration_Process_Metadata_Failed {
            get {
                return ResourceManager.GetString("Message_Fetch_integration_Process_Metadata_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Cache Prepration Completed: {0} Records to be Processed.
        /// </summary>
        internal static string Message_Integration_Process_Cache_Prepration_Completed {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Cache_Prepration_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Metadata Consume Source Succeeded : [Process Code={0}], Number of Source Records : {1}.
        /// </summary>
        internal static string Message_Integration_Process_ConsumeSource_Succeeded {
            get {
                return ResourceManager.GetString("Message_Integration_Process_ConsumeSource_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Execution Failed : [Process Code={0}].
        /// </summary>
        internal static string Message_Integration_Process_Execution_Failed {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Execution_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Start Request : [Process Code={0}].
        /// </summary>
        internal static string Message_Integration_Process_Execution_Start_Request {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Execution_Start_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Started : [Process Code={0}, Process ID={1}, Process Title={2}].
        /// </summary>
        internal static string Message_Integration_Process_Execution_Started {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Execution_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Execution Succeeded : [Process Code={0}].
        /// </summary>
        internal static string Message_Integration_Process_Execution_Succeeded {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Execution_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Metadata Validation Succeeded : [Process Code={0}].
        /// </summary>
        internal static string Message_Integration_Process_Validation_Succeeded {
            get {
                return ResourceManager.GetString("Message_Integration_Process_Validation_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Process Metadata Validation Failed - [Process Code={0}]{1}{2}.
        /// </summary>
        internal static string Message_Metadata_Validation_Failed {
            get {
                return ResourceManager.GetString("Message_Metadata_Validation_Failed", resourceCulture);
            }
        }
    }
}
